config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("movierama.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("movies/", include("movierama.movies.urls", namespace="movies")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

movierama/movies/urls.py
from django.urls import path

from . import views

app_name = "movies"
urlpatterns = [
    path("", views.movie_list, name="movie_list"),
    path("my_movies/", views.my_movie_list, name="my_movie_list"),
    path("user_movies/", views.user_movie_list, name="user_movie_list"),
    path("movie_users/", views.movie_user_list, name="movie_user_list"),
    path("user_votes/", views.user_vote_list, name="user_vote_list"),
    path("new/", views.movie_create, name="movie_new"),
    path("edit/<int:pk>/", views.movie_update, name="movie_edit"),
    path("delete/<int:pk>/", views.movie_delete, name="movie_delete"),
    path("vote_movies/", views.vote_movies, name="vote_movies"),
    path("movie_vote/<int:pk>/", views.movie_vote, name="movie_vote"),
]

movierama/users/urls.py
from django.urls import path

from movierama.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

movierama/movies/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from vote.models import VoteModel


class Movie(VoteModel, models.Model):
    """
    Stores a single movie, related to :model:`auth.User`.
    """

    title = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=1000)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    pub_date = models.DateTimeField("date published", auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movies:movie_edit", kwargs={"pk": self.pk})

movierama/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for MovieRama.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

movierama/movies/forms.py
from django.forms import CharField, ChoiceField, Form, ModelForm, RadioSelect, Textarea

from .models import Movie

VOTE_CHOICES = [
    ("like", "Like"),
    ("dislike", "Dislike"),
    ("remove", "Remove existing vote"),
]


class MovieForm(ModelForm):
    description = CharField(widget=Textarea())

    class Meta:
        model = Movie
        fields = ["title", "description"]


class VoteForm(Form):
    vote = ChoiceField(choices=VOTE_CHOICES, widget=RadioSelect())

movierama/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

movierama/movies/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from vote.models import DOWN, UP

from movierama.users.models import User

from .filters import MovieUserFilter
from .forms import MovieForm, VoteForm
from .models import Movie


def movie_list(request, template_name="movies/movie_list.html"):
    movies = Movie.objects.all()
    data = {}
    data["object_list"] = movies
    return render(request, template_name, data)


@login_required
def movie_user_list(request):
    f = MovieUserFilter(request.GET, queryset=Movie.objects.all())
    paginator = Paginator(f.qs.all(), 5)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, "movies/movie_user_list.html", {"user_movies": page_obj, "filter": f}
    )


@login_required
def movie_vote(request, pk, template_name="movies/movie_vote_form.html"):
    movie = get_object_or_404(Movie, pk=pk)
    form = VoteForm(request.POST or None)

    # Voting logic
    if form.is_valid():
        cd = form.cleaned_data

        # Remove vote if user already voted before
        if movie.votes.exists(request.user.id, action=UP) or movie.votes.exists(
            request.user.id, action=DOWN
        ):
            movie.votes.delete(request.user.id)

        # Revote according to user's choice
        if cd["vote"] == "like":
            movie.votes.up(request.user.id)
        elif cd["vote"] == "dislike":
            movie.votes.down(request.user.id)
        else:
            pass

        return redirect("movies:vote_movies")
    return render(request, template_name, {"form": form})


@login_required
def vote_movies(request, template_name="movies/vote_movies.html"):
    movies = Movie.objects.exclude(user=request.user).all()
    for movie in movies:
        my_vote = "have not voted"
        if movie.votes.exists(request.user.id):
            my_vote = "liked"
        elif movie.votes.exists(request.user.id, action=DOWN):
            my_vote = "disliked"
        movie.my_vote = my_vote

    data = {}
    data["object_list"] = movies
    return render(request, template_name, data)


@login_required
def my_movie_list(request, template_name="movies/my_movie_list.html"):
    movies = Movie.objects.filter(user=request.user).all()
    data = {}
    data["object_list"] = movies
    return render(request, template_name, data)


@login_required
def user_movie_list(request, template_name="movies/user_movie_list.html"):
    user_movies = {}
    users = User.objects.all()

    for user in users:
        movies = Movie.objects.filter(user=user).all()
        user_movies.update({user: movies})

    data = {}
    data["object_list"] = user_movies
    return render(request, template_name, data)


@login_required
def user_vote_list(request, template_name="movies/user_vote_list.html"):
    user_movies = {}
    users = User.objects.all()

    for user in users:
        movies_liked = Movie.votes.all(user.id, action=UP)
        movies_disliked = Movie.votes.all(user.id, action=DOWN)
        user_movies.update({user: {"liked": movies_liked, "disliked": movies_disliked}})

    data = {}
    data["object_list"] = user_movies
    return render(request, template_name, data)


@login_required
def movie_create(request, template_name="movies/movie_form.html"):
    form = MovieForm(request.POST or None)
    if form.is_valid():
        movie = form.save(commit=False)
        movie.user = request.user
        movie.save()
        return redirect("movies:my_movie_list")
    return render(request, template_name, {"form": form})


@login_required
def movie_update(request, pk, template_name="movies/movie_form.html"):
    if request.user.is_superuser:
        movie = get_object_or_404(Movie, pk=pk)
    else:
        movie = get_object_or_404(Movie, pk=pk, user=request.user)
    form = MovieForm(request.POST or None, instance=movie)
    if form.is_valid():
        form.save()
        return redirect("movies:movie_list")
    return render(request, template_name, {"form": form})


@login_required
def movie_delete(request, pk, template_name="movies/movie_confirm_delete.html"):
    if request.user.is_superuser:
        movie = get_object_or_404(Movie, pk=pk)
    else:
        movie = get_object_or_404(Movie, pk=pk, user=request.user)
    if request.method == "POST":
        movie.delete()
        return redirect("movies:movie_list")
    return render(request, template_name, {"object": movie})

movierama/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

movierama/templates/movies/movie_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'movies:movie_list' %}">Movies</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

movierama/templates/movies/movie_form.html
{% extends "base.html" %}

{% block content %}

<h4><a href="{% url 'movies:movie_list' %}">Add Movie</a></h4>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

movierama/templates/movies/movie_list.html
{% extends "base.html" %}

{% load render_table from django_tables2 %}

{% block content %}
<h4><a href="{% url 'movies:movie_list' %}">Movies Table</a></h4>
<p>All movies submitted by all Users. Displays number of "likes", "hates" and a total score.</p>
{% render_table object_list %}
{% endblock %}

movierama/templates/movies/movie_user_list.html
{% extends "base.html" %}

{% block content %}
<h4><a href="{% url 'movies:movie_user_list' %}">User Movies</a></h4>
<p>Filter on a username to narrow down the list of movies.</p>

<form method="get">
    {{ filter.form.as_p }}
    <input type="submit" />
</form>
  {% for movie in user_movies %}
    <ul>
        <li>
          <b>{{ movie.title }}</b> [likes:{{ movie.num_vote_up }} - hates:{{ movie.num_vote_down }}] submitted on {{ movie.pub_date }} by {{ movie.user.username }}
        </li>
        Description: {{ movie.description }}
    </ul>
  {% endfor %}
  <div class="pagination">
    <span class="step-links">
        {% if user_movies.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ user_movies.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ user_movies.number }} of {{ user_movies.paginator.num_pages }}.
        </span>

        {% if user_movies.has_next %}
            <a href="?page={{ user_movies.next_page_number }}">next</a>
            <a href="?page={{ user_movies.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

movierama/templates/movies/movie_vote_form.html
{% extends "base.html" %}

{% block content %}

<h4><a href="{% url 'movies:vote_movies' %}">Vote Movie</a></h4>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

movierama/templates/movies/my_movie_list.html
{% extends "base.html" %}

{% block content %}

<h4><a href="{% url 'movies:my_movie_list' %}">My Movies</a></h4>
<p>The movies you have submitted. Click on the links to edit or delete one of them.</p>

<ul>
    {% for movie in object_list %}
    <li><b>{{ movie.title }}</b>  ({{ movie.description }}) [likes:{{ movie.num_vote_up }} - hates:{{ movie.num_vote_down }}] by {{ movie.user.username }} on {{ movie.pub_date }}
    <a href="{% url 'movies:movie_edit' movie.id %}">edit</a>
    <a href="{% url 'movies:movie_delete' movie.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'movies:movie_new' %}">New</a>

{% endblock %}

movierama/templates/movies/user_movie_list.html
{% extends "base.html" %}

{% block content %}
<h4><a href="{% url 'movies:user_movie_list' %}">User Movies</a></h4>
<p>List of Movies submitted by each User. Click on a username to expand the list of user movies.</p>

<a href="{% url 'movies:movie_user_list' %}" class="btn btn-info" role="button">Filter User</a>


<div class="accordion accordion-flush" id="accordionFlushExample">
  {% for user, movies in object_list.items %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-heading{{ user.id }}">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ user.id }}" aria-expanded="false" aria-controls="flush-collapse{{ user.id }}">
        {{ user.username }}
      </button>
    </h2>
    <div id="flush-collapse{{ user.id }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ user.id }}" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        {% for movie in movies %}
        <ul>
            <li>
              <b>{{ movie.title }}</b> [likes:{{ movie.num_vote_up }} - hates:{{ movie.num_vote_down }}] submitted on {{ movie.pub_date }}
            </li>
            Description: {{ movie.description }}
        </ul>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

movierama/templates/movies/user_vote_list.html
{% extends "base.html" %}

{% block content %}
<h4><a href="{% url 'movies:user_vote_list' %}">User Votes</a></h4>
<p>List of movie Votes by each User. Click on a username to expand the list of user movie votes.</p>


<div class="accordion accordion-flush" id="accordionFlushExample">
  {% for user, movies in object_list.items %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-heading{{ user.id }}">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ user.id }}" aria-expanded="false" aria-controls="flush-collapse{{ user.id }}">
        {{ user.username }}
      </button>
    </h2>
    <div id="flush-collapse{{ user.id }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ user.id }}" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">

        <b>Liked</b>
        {% for movie in movies.liked %}
        <ul>
            <li> {{ movie.title }} [likes:{{ movie.num_vote_up }} - hates:{{ movie.num_vote_down }}] added on {{ movie.pub_date }} <b>- like</b>
            </li>
            Description: {{ movie.description }}
        </ul>
        {% endfor %}

        <b>Disliked</b>
        {% for movie in movies.disliked %}
        <ul>
            <li> {{ movie.title }} [likes:{{ movie.num_vote_up }} - hates:{{ movie.num_vote_down }}] added on {{ movie.pub_date }} <b>- dislike</b>
            </li>
            Description: {{ movie.description }}
        </ul>
        {% endfor %}

      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

movierama/templates/movies/vote_movies.html
{% extends "base.html" %}

{% block content %}

<h4><a href="{% url 'movies:vote_movies' %}">Vote Movies</a></h4>
<p>Like, hate or remove your vote on a Movie. You are not allowed to vote your own movies and are only allowed one vote per movie.</p>

<ul>
    {% for movie in object_list %}
    <li><b>{{ movie.title }}</b> [likes:{{ movie.num_vote_up }} - hates:{{ movie.num_vote_down }}] by {{ movie.user.username }} on {{ movie.pub_date }}
    <a href="{% url 'movies:movie_vote' movie.id %}">vote</a>
    <b>- You {{ movie.my_vote }}!</b>
    </li>
    Description: {{ movie.description }}
    {% endfor %}
</ul>

{% endblock %}